### ISSUE TITLE
AEM content transfer tool issue

### ISSUE THREAD

**Issue by satish99999** [AdobeDocs/experience-manager-cloud-service.en#1]
Issue in ./help/journey-migration/content-transfer-tool/using-content-transfer-tool/getting-started-content-transfer-tool.md

Hi Team,

while we running extraction on the AEM source server we are getting the below error.
we have enabled the below three domains from our source firewall to the destination server.

The target AEM as a Cloud Service environment: author-p<program_id>-e<env_id>.adobeaemcloud.com
The Azure blob storage service: casstorageprod.blob.core.windows.net
The User Mapping IO endpoint: usermanagement.adobe.io
could you please help us with the below error?

we are using v1.9.2 CTT version.

2022-08-21 05:50:40,154 [main] INFO  c.a.granite.skyline.migrator.Main - Error in migration
com.microsoft.azure.storage.StorageException: An unknown failure occurred : Connection timed out (Connection timed out)
	at com.microsoft.azure.storage.StorageException.translateException(StorageException.java:67)
	at com.microsoft.azure.storage.core.ExecutionEngine.executeWithRetry(ExecutionEngine.java:220)
	at com.microsoft.azure.storage.blob.CloudBlob.exists(CloudBlob.java:2073)
	at com.microsoft.azure.storage.blob.CloudBlob.exists(CloudBlob.java:2060)
	at com.microsoft.azure.storage.blob.CloudBlob.exists(CloudBlob.java:2035)
	at com.adobe.granite.skyline.commons.AzureReadWriteLockUtils.acquireLease(AzureReadWriteLockUtils.java:172)
	at com.adobe.granite.skyline.commons.AzureReadWriteLockUtils.writeLock(AzureReadWriteLockUtils.java:120)
	at com.adobe.granite.skyline.migrator.Main.runExtraction(Main.java:151)
	at com.adobe.granite.skyline.migrator.Main.main(Main.java:121)
Caused by: java.net.ConnectException: Connection timed out (Connection timed out)
	at java.net.PlainSocketImpl.socketConnect(Native Method)
	at java.net.AbstractPlainSocketImpl.doConnect(AbstractPlainSocketImpl.java:476)
	at java.net.AbstractPlainSocketImpl.connectToAddress(AbstractPlainSocketImpl.java:218)
	at java.net.AbstractPlainSocketImpl.connect(AbstractPlainSocketImpl.java:200)
	at java.net.SocksSocketImpl.connect(SocksSocketImpl.java:394)
	at java.net.Socket.connect(Socket.java:606)
	at sun.security.ssl.SSLSocketImpl.connect(SSLSocketImpl.java:303)
	at sun.net.NetworkClient.doConnect(NetworkClient.java:175)
	at sun.net.www.http.HttpClient.openServer(HttpClient.java:499)
	at sun.net.www.http.HttpClient.openServer(HttpClient.java:594)
	at sun.net.www.protocol.https.HttpsClient.<init>(HttpsClient.java:263)
	at sun.net.www.protocol.https.HttpsClient.New(HttpsClient.java:366)
	at sun.net.www.protocol.https.AbstractDelegateHttpsURLConnection.getNewHttpClient(AbstractDelegateHttpsURLConnection.java:207)
	at sun.net.www.protocol.http.HttpURLConnection.plainConnect0(HttpURLConnection.java:1167)
	at sun.net.www.protocol.http.HttpURLConnection.plainConnect(HttpURLConnection.java:1061)
	at sun.net.www.protocol.https.AbstractDelegateHttpsURLConnection.connect(AbstractDelegateHttpsURLConnection.java:193)
	at sun.net.www.protocol.http.HttpURLConnection.getInputStream0(HttpURLConnection.java:1584)
	at sun.net.www.protocol.http.HttpURLConnection.getInputStream(HttpURLConnection.java:1512)
	at java.net.HttpURLConnection.getResponseCode(HttpURLConnection.java:480)
	at sun.net.www.protocol.https.HttpsURLConnectionImpl.getResponseCode(HttpsURLConnectionImpl.java:352)
	at com.microsoft.azure.storage.core.ExecutionEngine.executeWithRetry(ExecutionEngine.java:115)
	... 7 common frames omitted
2022-08-21 05:50:40,155 [main] ERROR c.a.granite.skyline.migrator.Main - Can't finish extraction
java.lang.RuntimeException: com.microsoft.azure.storage.StorageException: An unknown failure occurred : Connection timed out (Connection timed out)
	at com.google.common.io.Closer.rethrow(Closer.java:149)
	at com.adobe.granite.skyline.migrator.Main.runExtraction(Main.java:174)
	at com.adobe.granite.skyline.migrator.Main.main(Main.java:121)
Caused by: com.microsoft.azure.storage.StorageException: An unknown failure occurred : Connection timed out (Connection timed out)

**Comment by anujkapo** [comment]
Thanks, @satish99999 for the issue description, however, this seems to be a query on how to use the product. This platform is used for reporting issues in Experience Manager as a Cloud Service documentation. You can contact our Customer Care team:
https://experienceleague.adobe.com/?support-solution=Experience+Manager#home

**Comment by aheim0** [comment]
No further response.
Closing issue.
